name: Sync Vercel Files to GitHub

on:
  push:
    branches:
      - master  # 根据你的需求调整分支名称

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 检出 GitHub 仓库代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 下载 Vercel 部署文件
      - name: Download files from Vercel
        run: |
          curl -L -o vercel_deploy.zip https://vercel.com/fnvtks-projects/cunkebao-v2/J6YTApbZU73GiwJ9bumRdGRrMA4Q
          unzip vercel_deploy.zip -d vercel_files

      # 将文件同步到 GitHub
      - name: Commit and Push Vercel files to GitHub
        run: |
          git config user.name "fnvtk"
          git config user.email "zhiqun@qq.com"
          cp -r vercel_files/* .
          git add .
          git commit -m "Sync updates from Vercel" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/fnvtk/cunkebao_v2.git master
