name: Sync Vercel Files to GitHub

on:
  push:
    branches:
      - master  # 你可以根据需要修改为你部署的分支

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download files from Vercel
        run: |
          curl -L -o vercel_deploy.zip https://vercel.com/fnvtks-projects/cunkebao-v2/J6YTApbZU73GiwJ9bumRdGRrMA4Q
          unzip vercel_deploy.zip -d vercel_files

      - name: Commit and Push Vercel files to GitHub
        run: |
          git config user.name "fnvtk"
          git config user.email "zhiqun@qq.com"
          # Use GitHub Token for authentication
          git config --global credential.helper store
          echo "https://$GITHUB_TOKEN:@github.com" > ~/.git-credentials
          cp -r vercel_files/* .
          git add .
          git commit -m "Sync updates from Vercel"
          git push https://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@github.com/fnvtk/cunkebao_v2.git master
